### PR TITLE
pt_BR localization

### PR DESCRIPTION
**Pull request by thiagoeec**
- Adds pt_BR localization for Ace messages

### CODE REVIEW

**Comment by danielweck** [comment]
Related issue (closed):
https://github.com/daisy/ace/issues/216

**Comment by danielweck** [comment]
This "looks good" to me - i.e. I have not tested the translation, neither manually, nor in an automated manner using a l10n tool (e.g. to compare JSON keys with the "master" `en` locale)

@rdeltour your call :)

**Comment by thiagoeec** [comment]
> This "looks good" to me - i.e. I have not tested the translation, neither manually, nor in an automated manner using a l10n tool (e.g. to compare JSON keys with the "master" `en` locale)

I've tested it manually against a couple of files and everything is working fine. But I didn't do any automated test.

**Comment by danielweck** [comment]
Hello, I have just introduced a tool to sort the JSON keys and check secondary language locales against the primary (`en`), in order to detect missing keys, and remove redundant / unused keys.

I will merge your PR as-is into a "staging" PR branch, then apply the sorting + checks, then create a new PR against `master`.

**Comment by danielweck** [comment]
Follow-up PR: https://github.com/daisy/ace/pull/258

**Pull request merged**
