### PR TITLE
feat: pt_BR localization

### PR DESCRIPTION
**Pull request by danielweck**
Follow-up to PR: https://github.com/daisy/ace/pull/246

Changes: sorted JSON keys, checked for invalid keys (missing, unused)

### CODE REVIEW

**Comment by danielweck** [comment]
Many thanks to @thiagoeec !

**Comment by danielweck** [comment]
Related PRs:
https://github.com/daisy/ace-gui/pull/60
https://github.com/daisy/ace-gui/pull/63

**Comment by danielweck** [comment]
Dear @thiagoeec thanks to your contribution, both the Ace CLI and the Ace App support an additional language. However, Axe (the library used internally to perform accessibility checks for individual web pages) is a separate project that maintains its own translations. Please note that you might have to contribute there too in order for your locale to be supported end-to-end. Please refer to this information:
https://github.com/daisy/ace/wiki/Localization#axe-localization

**Comment by thiagoeec** [comment]
> Dear @thiagoeec thanks to your contribution, both the Ace CLI and the Ace App support an additional language.

Ace is a great tool. I'm glad to help, @danielweck. 

>Please note that you might have to contribute there too in order for your locale to be supported end-to-end.

I'm currently translating Axe (about 50% done). I will open a PR when its done.

**Comment by thiagoeec** [comment]
Hi guys.

It's been more than a year since pt_BR (and also Spanish) was added, but no release was made.
What is holding on the release?

**Comment by danielweck** [comment]
Hello, this PR was merged into the master branch which is used for the "legacy" 1.1.x Ace releases, and published to NPM under the "latest" tag (currently version 1.1.1):
https://www.npmjs.com/package/@daisy/ace/v/latest

However a newer version of Ace has been evolving in a separate branch in order to meet the requirements of Ace App (GUI), and this version 1.2.x has been published as a "beta" under the NPM tag "next":
https://www.npmjs.com/package/@daisy/ace/v/next

The goal is to deprecate 1.1.x. (which supports older versions of NodeJS, now obsolete and not secure) and to officialise 1.2.x in the coming weeks / months (user feedback for Ace App / GUI has not shown any signs that Ace 1.2.x introduced regression bugs in terms of accuracy or performance, so it seems appropriate to recommend the upgrade for CLI users too).

**Comment by danielweck** [comment]
supported locales in the ace-next branch: https://github.com/daisy/ace/tree/ace-next/packages/ace-report/src/l10n/locales

**Comment by danielweck** [comment]
supported locales in master versus release tag 1.1.1:

https://github.com/daisy/ace/tree/master/packages/ace-report/src/l10n/locales

https://github.com/daisy/ace/tree/v1.1.1/packages/ace-report/src/l10n/locales

**Comment by danielweck** [comment]
Another very important point: newer versions of Axe include locales that were contributed at the same time as Ace (cli and gui). But as Ace 1.1.x releases are based on an older revision of Axe, they do not inherit the locale contributions from Axe. Conversely, Ace 1.2..x track the latest package dependencies, so the locale translations are synchronized in Axe, Ace and Ace App.

**Pull request merged**
