### PR TITLE
fixes #273 (DAISY KnowledgeBase ARIA entry for landmark-is-unique Axe check)

### LINKED ISSUE #273: unique aria-label / title for landmarks (Invalid Link to KB)
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [10.16.0] the version of Node used to run Ace (as returned by the `node -v` command).
- [Mac 10.14] your operating system and version.

Invalid link to KB

The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable
Learn more about: (no specific entry)

### PR DESCRIPTION
**Pull request by danielweck**
Fixes https://github.com/daisy/ace/issues/273

### CODE REVIEW

**Comment by danielweck** [comment]
I wonder how many other Axe checks/rules need KnowledgeBase mapping?
See:
https://github.com/dequelabs/axe-core/tree/master/lib/checks
https://github.com/dequelabs/axe-core/tree/master/lib/rules

**Comment by danielweck** [comment]
Note that in this PR I am reusing `title: localize("kb.aria-roles")` instead of unnecessarily creating a new translation ... they all say "ARIA" anyway:
https://github.com/daisy/ace/blob/5d4cc866af8141180980522748c0aa82830afb7a/packages/ace-report-axe/src/l10n/locales/en.json#L5-L12

**Comment by danielweck** [comment]
Hello @rdeltour do you have any thoughts about the second comment in this PR?

**Comment by rdeltour** [comment]
> I wonder how many other Axe checks/rules need KnowledgeBase mapping?

As far as I remembers, the keys in this mapping are rule names. I think we used Axe's API to return the list of rules that were enabled in the version we use to build this map.

**Comment by danielweck** [comment]
PR superseded with https://github.com/daisy/ace/pull/299

**Pull request closed without merging**
